Repository fabric8-services/fabric8-wit, pull requests merged in 2018-07, with the labels that each got.

#2180 Refactor wi_link_blackbox_test: Remove unnecessary code
  controller/work_item_link_blackbox_test.go
Labels: :bath: cleanup

#2185 Added workitem.GormWorkItemTypeRepository.CreateFromModel
  test/testfixture/make_functions.go
  workitem/workitemtype_repository.go
Labels: :bath: cleanup, :recycle: refactoring

#2188 Remove flow-heater container if it already exists
  cico_setup.sh
Labels: :bath: cleanup, :package: build system

#2169 521 create root api
  .gofmt_exclude
  Makefile
  controller/endpoints.go
  controller/endpoints_blackbox_test.go
  controller/test-files/endpoints/list/not_found.res.headers.golden.json
  controller/test-files/endpoints/list/not_found.res.payload.golden.json
  controller/test-files/endpoints/list/ok.res.headers.golden.json
  controller/test-files/endpoints/list/ok.res.payload.golden.json
  controller/workitemtype_blackbox_test.go
  design/account.go
  design/endpoints.go
  jsonapi/jsonapi_utility.go
  jsonapi/jsonapi_utility_blackbox_test.go
  main.go
Labels: :bomb: test, jsonapi
