Repository fabric8-services/fabric8-wit, pull requests merged in 2018-04, with the labels that each got.

#1980 Add id.Slice.ToMap and id.Slice.ToStringSlice
  id/slice.go
  id/slice_blackbox_test.go
Labels: space_templates

#1982 Only log JSON API compliance errors when not valid
  controller/json_api_compliance_test.go
Labels: space_templates

#1981 Refactor iteration test func createSpaceAndRootAreaAndIterations
  controller/iteration_blackbox_test.go
  controller/workitem_blackbox_test.go
Labels: space_templates

#1983 Fix comment on repository.Exister.CheckExists
  application/repository/exister.go
Labels: space_templates

#1989 Separate "list" and "show" action of WIT and WILT
  controller/comments_blackbox_test.go
  controller/search_blackbox_test.go
  controller/test-files/search/show/filter_assignee_null_show_after_update_work_item.golden.json
  controller/test-files/search/show/filter_assignee_null_update_work_item.golden.json
  controller/test-files/search/show/filter_label_null_show_after_update_work_item.golden.json
  controller/test-files/search/show/filter_label_null_update_work_item.golden.json
  controller/test-files/search/show/in_topology_A-B-C-D_and_B-E_search_for_B_and_C/do_not_include_children.res.payload.golden.json
  controller/test-files/search/show/in_topology_A-B-C-D_and_B-E_search_for_B_and_C/include_children.res.payload.golden.json
  controller/test-files/search/show/in_topology_A-B-C_and_A-D_search_for/A_with_tree-view=false.res.golden.json
  controller/test-files/search/show/in_topology_A-B-C_and_A-D_search_for/A_with_tree-view=true.res.golden.json
  controller/test-files/search/show/in_topology_A-B-C_and_A-D_search_for/B,C_with_tree-view=false.res.golden.json
  controller/test-files/search/show/in_topology_A-B-C_and_A-D_search_for/B,C_with_tree-view=true.res.golden.json
  controller/test-files/search/show/in_topology_A-B-C_and_A-D_search_for/B_with_tree-view=false.res.golden.json
  controller/test-files/search/show/in_topology_A-B-C_and_A-D_search_for/B_with_tree-view=true.res.golden.json
  controller/test-files/search/show/in_topology_A-B-C_and_A-D_search_for/C_with_tree-view=false.res.golden.json
  controller/test-files/search/show/in_topology_A-B-C_and_A-D_search_for/C_with_tree-view=true.res.golden.json
  controller/test-files/search/show/in_topology_A-B-C_and_A-D_search_for/D_with_tree-view=false.res.golden.json
  controller/test-files/search/show/in_topology_A-B-C_and_A-D_search_for/D_with_tree-view=true.res.golden.json
  controller/test-files/search/show/in_topology_A-B-C_and_A-D_search_for/E_with_tree-view=false.res.golden.json
  controller/test-files/search/show/in_topology_A-B-C_and_A-D_search_for/E_with_tree-view=true.res.golden.json
  controller/test-files/work_item_link/create/ok.req.payload.golden.json
  controller/test-files/work_item_link/create/ok.res.payload.golden.json
  controller/test-files/work_item_link/list/ok.res.paylpad.golden.json
  controller/test-files/work_item_link/show/ok.res.payload.golden.json
  controller/test-files/work_item_link_type/list/ok.res.payload.golden.json
  controller/test-files/work_item_link_type/list/ok_using_expired_ifmodifiedsince_header.res.payload.golden.json
  controller/test-files/work_item_link_type/list/ok_using_expired_ifnonematch_header.res.payload.golden.json
  controller/test-files/work_item_link_type/show/ok.res.payload.golden.json
  controller/test-files/work_item_link_type/show/ok_using_expired_ifmodifiedsince_header.res.payload.golden.json
  controller/test-files/work_item_link_type/show/ok_using_expired_ifnonematch_header.res.payload.golden.json
  controller/work_item_link.go
  controller/work_item_link_blackbox_test.go
  controller/work_item_link_type.go
  controller/work_item_link_type_blackbox_test.go
  controller/work_item_link_types.go
  controller/work_item_link_types_blackbox_test.go
  controller/workitem.go
  controller/workitem_blackbox_test.go
  controller/workitem_whitebox_test.go
  controller/workitemtype.go
  controller/workitemtype_blackbox_test.go
  controller/workitemtypes.go
  controller/workitemtypes_blackbox_test.go
  design/work_item_link_type.go
  design/workitemtype.go
  main.go
  workitem/workitemtype_repository.go
  workitem/workitemtype_repository_bench_test.go
  workitem/workitemtype_repository_blackbox_test.go
Labels: :bath: cleanup, :bomb: test, :recycle: refactoring, jsonapi, space_templates

#1991 Add missing wilt repo test
  controller/test-files/work_item_link_type/list/not_found_for_non_existing_space_id.res.headers.golden.json
  controller/test-files/work_item_link_type/list/not_found_for_non_existing_space_id.res.payload.golden.json
  controller/test-files/work_item_link_type/list/ok_for_non_existing_space_id.res.headers.golden.json
  controller/test-files/work_item_link_type/list/ok_for_non_existing_space_id.res.payload.golden.json
  controller/work_item_link_types_blackbox_test.go
  design/work_item_link_type.go
  workitem/link/type_repository.go
  workitem/link/type_repository_blackbox_test.go
Labels: :bomb: test, space_templates

#1993 Fix comments, use errs and check for interface implementation
  workitem/field_test_data.go
  workitem/json_storage.go
Labels: :bath: cleanup, documentation, space_templates

#2000 Use account.KeycloakIDP instead of "test provider"
  test/testfixture/make_functions.go
Labels: :bomb: test

#1996 fix system.number field storage and add read-only fields
  .golint_exclude
  controller/test-files/work_item_type/list/ok.res.payload.golden.json
  controller/test-files/work_item_type/list/ok_using_expired_ifmodifiedsince_header.res.payload.golden.json
  controller/test-files/work_item_type/list/ok_using_expired_ifnonematch_header.res.payload.golden.json
  controller/test-files/work_item_type/show/ok.wit.golden.json
  controller/test-files/work_item_type/show/ok_using_expired_etag_header.wit.golden.json
  controller/test-files/work_item_type/show/ok_using_expired_lastmodified_header.wit.golden.json
  migration/migration.go
  migration/migration_blackbox_test.go
  migration/sql-files/085-delete-system.number-json-field.sql
  migration/sql-test-files/085-delete-system.number-json-field.sql
  test/testfixture/make_functions.go
  workitem/enum_type.go
  workitem/field_definition.go
  workitem/field_definition_whitebox_test.go
  workitem/list_type.go
  workitem/simple_type.go
  workitem/workitem_repository.go
  workitem/workitem_repository_blackbox_test.go
Labels: :bomb: test, :grey_exclamation: important, :see_no_evil: bug, database, jsonapi, space_templates

#2008 Improve and clean WIT creation
  controller/planner_backlog_bench_test.go
  controller/planner_backlog_blackbox_bench_test.go
  controller/planner_backlog_blackbox_test.go
  controller/planner_backlog_test.go
  controller/test-files/work_item_type/list/ok.res.payload.golden.json
  controller/test-files/work_item_type/list/ok_using_expired_ifmodifiedsince_header.res.payload.golden.json
  controller/test-files/work_item_type/list/ok_using_expired_ifnonematch_header.res.payload.golden.json
  controller/test-files/work_item_type/show/ok.wit.golden.json
  controller/test-files/work_item_type/show/ok_using_expired_etag_header.wit.golden.json
  controller/test-files/work_item_type/show/ok_using_expired_lastmodified_header.wit.golden.json
  controller/workitem_blackbox_test.go
  controller/workitemtype.go
  controller/workitemtype_whitebox_test.go
  design/workitemtype.go
  migration/migration.go
  migration/migration_blackbox_test.go
  migration/sql-files/086-add-can-construct-to-wit.sql
  search/search_repository.go
  search/search_repository_blackbox_test.go
  test/testfixture/make_functions.go
  workitem/link/link_repository.go
  workitem/workitem_repository.go
  workitem/workitem_repository_blackbox_test.go
  workitem/workitemtype.go
  workitem/workitemtype_blackbox_test.go
  workitem/workitemtype_repository.go
  workitem/workitemtype_repository_blackbox_test.go
Labels: :bath: cleanup, :bomb: test, database, space_templates

#2015 Generate String() for app.JSONAPIErrors
  Makefile
  goasupport/jsonapi_errors_stringer/generator.go
Labels: :memo: logging, cli, jsonapi

#2012 improve replacement for times in golden files
  controller/golden_files_test.go
Labels: :bomb: test, enhancement

#2033 Fix db migration space templates
  migration/migration.go
  migration/migration_blackbox_test.go
  migration/sql-files/087-space-templates.sql
  migration/sql-test-files/087-space-templates.sql
Labels: :see_no_evil: bug, database

#2035 Fixup for DB migration
  migration/migration.go
  migration/migration_blackbox_test.go
  migration/sql-files/087-space-templates.sql
  migration/sql-files/089-fixup-space-templates.sql
  migration/sql-test-files/087-space-templates.sql
Labels: :see_no_evil: bug, database

#2040 Temporarily disable golint
  Gopkg.lock
  Gopkg.toml
  Makefile
Labels: :grey_exclamation: important, :package: build system, :rotating_light: URGENT

#2039 Rework forward and reverse link names
  controller/test-files/work_item_link_type/list/ok.res.payload.golden.json
  controller/test-files/work_item_link_type/list/ok_using_expired_ifmodifiedsince_header.res.payload.golden.json
  controller/test-files/work_item_link_type/list/ok_using_expired_ifnonematch_header.res.payload.golden.json
  spacetemplate/assets/base.yaml
Labels: :bath: cleanup, :sparkles: UI

#2053 data conflict (409) on link cycle detection instead internal server error (500)
  controller/test-files/work_item_link/create/link_cycle_detected.res.headers.golden.json
  controller/test-files/work_item_link/create/link_cycle_detected.res.payload.golden.json
  controller/work_item_link_blackbox_test.go
  workitem/link/link_repository.go
Labels: :sleeping: REST, jsonapi

#2049 Revert "Temporarily disable golint (#2040)"
  Gopkg.lock
  Gopkg.toml
  Makefile
Labels: :package: build system, :robot: bot, :snake: security

#2055 Rename Openshift.io Legacy Template to Scenario Driven Development
  controller/space_template_blackbox_test.go
  controller/test-files/space_templates/show/ok_base_template.res.headers.golden.json
  controller/test-files/space_templates/show/ok_base_template.res.payload.golden.json
  controller/test-files/space_templates/show/ok_generated_template.res.headers.golden.json
  controller/test-files/space_templates/show/ok_generated_template.res.payload.golden.json
  controller/test-files/space_templates/show/ok_legacy_template.res.headers.golden.json
  controller/test-files/space_templates/show/ok_legacy_template.res.payload.golden.json
  controller/test-files/space_templates/show/ok_scrum_template.res.headers.golden.json
  controller/test-files/space_templates/show/ok_scrum_template.res.payload.golden.json
  spacetemplate/assets/legacy.yaml
Labels: documentation

#2056 Add PBI and bug to scrum execution typegroup
  controller/golden_files_test.go
  controller/test-files/work_item_type_group/list/ok_base_template.headers.golden.json
  controller/test-files/work_item_type_group/list/ok_base_template.payload.golden.json
  controller/test-files/work_item_type_group/list/ok_generated_template.headers.golden.json
  controller/test-files/work_item_type_group/list/ok_generated_template.payload.golden.json
  controller/test-files/work_item_type_group/list/ok_legacy_template.headers.golden.json
  controller/test-files/work_item_type_group/list/ok_legacy_template.payload.golden.json
  controller/test-files/work_item_type_group/list/ok_scrum_template.headers.golden.json
  controller/test-files/work_item_type_group/list/ok_scrum_template.payload.golden.json
  controller/work_item_type_group_blackbox_test.go
  spacetemplate/assets/legacy.yaml
  spacetemplate/assets/scrum.yaml
  workitem/typegroup_repository.go
Labels: :bath: cleanup, enhancement

#2057 Remove cached OSIO client object
  controller/deployments.go
Labels: :one: severity/P1, platform

#2067 Fix scrum icons
  Gopkg.lock
  controller/test-files/work_item_type/list/ok_base.res.headers.golden.json
  controller/test-files/work_item_type/list/ok_base.res.payload.golden.json
  controller/test-files/work_item_type/list/ok_legacy.res.headers.golden.json
  controller/test-files/work_item_type/list/ok_legacy.res.payload.golden.json
  controller/test-files/work_item_type/list/ok_scrum.res.headers.golden.json
  controller/test-files/work_item_type/list/ok_scrum.res.payload.golden.json
  controller/test-files/work_item_type_group/list/ok_scrum_template.payload.golden.json
  controller/workitemtypes_blackbox_test.go
  spacetemplate/assets/scrum.yaml
Labels: :bath: cleanup, :grey_exclamation: important, :rotating_light: URGENT, :sparkles: UI
